const axios = require('axios');

let conversationHistory = {}; // Store conversation history per thread

module.exports = {
  config: {
    name: 'autoresponse',
    version: '1.0.0',
    author: 'Jay Pillonar',
    role: 0,
    category: 'Auto Response',
    longDescription: {
      en: 'This bot responds to every message with a reply generated by the hercai API, providing responses in English with colloquial abbreviations and details about the owner.'
    },
    guide: {
      en: `
      Command: (No prefix needed)
      - This command responds to every message with a reply from the hercai API, in English with colloquial abbreviations. It includes information about the owner and personal details.
      `
    }
  },

  onStart: async () => {},

  onChat: async ({ api, event }) => {
    const userMessage = event.body.trim();
    const threadID = event.threadID;

    if (!userMessage || userMessage.startsWith('/')) return; // Ignore empty messages and messages starting with "/"

    // Initialize conversation history if it does not exist
    if (!conversationHistory[threadID]) {
      conversationHistory[threadID] = '';
    }

    // Append new message to conversation history
    conversationHistory[threadID] += `User: ${userMessage}\n`;

    // Prepare prompt for hercai API with the new details
    const hercai_prompt = `Responds in English humor with colloquial abbreviations. Her name is Mica, and she's owned by Jay. Mica is a helpful AI just like GPT-4. If anyone asks about the owner of AAG, Ace Advocates, Ace Advocates Group, the gang, the clan, or the group, Mica will always answer that Jay is the owner. Jay is a 14-year-old boy, a male with a current height of 5'5" (165 cm) and a weight of 49 kg. He plays Chess, Basketball, Takraw, and Badminton. The online games he enjoys are Roblox, Mobile Legends, and Call of Duty. Jay is good at studying and is a gentleman. User: ${userMessage}`;

    try {
      // Send the message to the hercai API for a response
      const response = await axios.post('https://hercai.onrender.com/v3/hercai', {
        question: hercai_prompt
      });

      if (response.status !== 200 || !response.data || !response.data.reply) {
        throw new Error('Invalid or missing response from API');
      }

      // Extract and format the API response
      const aiResponse = response.data.reply;

      // Update conversation history with bot response
      conversationHistory[threadID] += `Bot: ${aiResponse}\n`;

      // Reply with the generated message
      await api.sendMessage(aiResponse, threadID);

    } catch (error) {
      console.error(`Error fetching response: ${error.message}`);
      await api.sendMessage(`Sorry there was an error in your request😞. Error: ${error.message}`, threadID);
    }
  },

  onReply: async () => {
    // Handle replies if needed, otherwise leave this section empty or remove
  }
};
